p8105_hw2_fl2714
================
Fangchi
2024-09-29

## Problem 1:NYC Transit data

### Read and clean the data

``` r
subway_data <- read.csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

``` r
colnames(subway_data)
```

    ##  [1] "Division"           "Line"               "Station.Name"      
    ##  [4] "Station.Latitude"   "Station.Longitude"  "Route1"            
    ##  [7] "Route2"             "Route3"             "Route4"            
    ## [10] "Route5"             "Route6"             "Route7"            
    ## [13] "Route8"             "Route9"             "Route10"           
    ## [16] "Route11"            "Entrance.Type"      "Entry"             
    ## [19] "Exit.Only"          "Vending"            "Staffing"          
    ## [22] "Staff.Hours"        "ADA"                "ADA.Notes"         
    ## [25] "Free.Crossover"     "North.South.Street" "East.West.Street"  
    ## [28] "Corner"             "Entrance.Latitude"  "Entrance.Longitude"
    ## [31] "Station.Location"   "Entrance.Location"

``` r
# Clean and transform the data
subway_df <- subway_data |>
  janitor::clean_names() |>  # Clean the column names to be consistent
  mutate( 
    # Convert entry to logical
    entry_logic = ifelse(entry == "YES", TRUE, ifelse(entry == "NO", FALSE, NA)),
    # Count number of non-missing routes (treating both NA and "" as missing)
    route_count = rowSums(!is.na(across(starts_with("route"))) & across(starts_with("route"), ~ . != ""))
  ) |>
  # Select only the relevant columns
  select(line, station_name, station_latitude, station_longitude, 
         route_count, entry_logic, vending, entrance_type, ada)
```

``` r
sapply(subway_df, class)
```

    ##              line      station_name  station_latitude station_longitude 
    ##       "character"       "character"         "numeric"         "numeric" 
    ##       route_count       entry_logic           vending     entrance_type 
    ##         "numeric"         "logical"       "character"       "character" 
    ##               ada 
    ##         "logical"

``` r
# Count missing values for each column
colSums(is.na(subway_df))
```

    ##              line      station_name  station_latitude station_longitude 
    ##                 0                 0                 0                 0 
    ##       route_count       entry_logic           vending     entrance_type 
    ##                 0                 0                 0                 0 
    ##               ada 
    ##                 0

``` r
summary(subway_df)
```

    ##      line           station_name       station_latitude station_longitude
    ##  Length:1868        Length:1868        Min.   :40.58    Min.   :-74.03   
    ##  Class :character   Class :character   1st Qu.:40.69    1st Qu.:-73.99   
    ##  Mode  :character   Mode  :character   Median :40.73    Median :-73.96   
    ##                                        Mean   :40.73    Mean   :-73.94   
    ##                                        3rd Qu.:40.77    3rd Qu.:-73.91   
    ##                                        Max.   :40.90    Max.   :-73.76   
    ##   route_count     entry_logic       vending          entrance_type     
    ##  Min.   : 1.000   Mode :logical   Length:1868        Length:1868       
    ##  1st Qu.: 1.000   FALSE:115       Class :character   Class :character  
    ##  Median : 2.000   TRUE :1753      Mode  :character   Mode  :character  
    ##  Mean   : 2.286                                                        
    ##  3rd Qu.: 3.000                                                        
    ##  Max.   :11.000                                                        
    ##     ada         
    ##  Mode :logical  
    ##  FALSE:1400     
    ##  TRUE :468      
    ##                 
    ##                 
    ## 

``` r
# enumerate categorical variables
table(subway_df$entry_logic)
```

    ## 
    ## FALSE  TRUE 
    ##   115  1753

``` r
table(subway_df$vending)
```

    ## 
    ##   NO  YES 
    ##  183 1685

``` r
table(subway_df$entrance_type)
```

    ## 
    ##      Door  Easement  Elevator Escalator      Ramp     Stair   Walkway 
    ##        81        91        49        28         3      1615         1

``` r
table(subway_df$ada)
```

    ## 
    ## FALSE  TRUE 
    ##  1400   468

### Data description

The data we have preprocessed has 1868 rows and 9 rows.

- **line** (`Character`): The subway line.
- **station_name** (`Character`): The name of the subway station.
- **station_latitude** (`Numeric`): range from 40.58 to 40.90, with a
  median at 40.73.
- **station_longitude** (`Numeric`): range from -74.03 to -73.76, with a
  median at -73.96.
- **route_count** (`Numeric`): The number of routes available at each
  station is between 1 to 11, with an average of 2.286.
- **entry_logic** (`Logical`): Whether is an entrance, 1753 are `TRUE`
  and 115 are `FALSE`.
- **vending** (`Character`): Vending availability at the station, 1685
  are `YES` and 183 are `NO`.
- **entrance_type** (`Character`): Type of entrance. This variable
  describes the type of entrance each station has.
- **ada** (`Logical`): Whether the station is ADA accessible. 468 are
  `TRUE` and 1400 are `FALSE`.

### Data cleaning steps

- 1.**Data retrieval**: read data from csv
- 2.**Clean Column Names**: Standardize column names
- 3.**Calculate Entry Logic**: Convert the entry variable from character
  to a logical variable
- 4.**Determine Route Count**: Compute routes served at each station by
  counting non-missing values of columns indicate routes
- 5.**Select Columns**: Select columns we need
- 6.**Data Validation**: Check missing values, data type, categorical
  variable values, etc.

The data is tidy for Exploratory Data Analysis since there’s no missing
values, no anomalies in the numerical or categorical variables, and
clear meanings for all columns

### Exploratory Data Analysis

``` r
distinct_stations <- subway_df %>%
  distinct(station_name, line) %>%
  nrow()

distinct_stations
```

    ## [1] 465

There are 465 distinct stations.

``` r
# Counting ADA compliant stations
ada_compliant_stations <- subway_df %>%
  filter(ada == TRUE) %>%
  distinct(station_name, line) %>%
  nrow()

# Output the number of ADA compliant stations
ada_compliant_stations
```

    ## [1] 84

84 stations are ADA compliant

``` r
# Proportion of non-vending entrances that allow entry
non_vending_proportion <- subway_df %>%
  filter(vending == "NO") %>%
  summarize(proportion = mean(entry_logic, na.rm = TRUE))

# Output the proportion
non_vending_proportion$proportion
```

    ## [1] 0.3770492

37.7% of station entrances / exits without vending allow entrance

``` r
head(subway_data)
```

    ##   Division     Line Station.Name Station.Latitude Station.Longitude Route1
    ## 1      BMT 4 Avenue      25th St         40.66040         -73.99809      R
    ## 2      BMT 4 Avenue      25th St         40.66040         -73.99809      R
    ## 3      BMT 4 Avenue      36th St         40.65514         -74.00355      N
    ## 4      BMT 4 Avenue      36th St         40.65514         -74.00355      N
    ## 5      BMT 4 Avenue      36th St         40.65514         -74.00355      N
    ## 6      BMT 4 Avenue      45th St         40.64894         -74.01001      R
    ##   Route2 Route3 Route4 Route5 Route6 Route7 Route8 Route9 Route10 Route11
    ## 1                                               NA     NA      NA      NA
    ## 2                                               NA     NA      NA      NA
    ## 3      R                                        NA     NA      NA      NA
    ## 4      R                                        NA     NA      NA      NA
    ## 5      R                                        NA     NA      NA      NA
    ## 6                                               NA     NA      NA      NA
    ##   Entrance.Type Entry Exit.Only Vending Staffing Staff.Hours   ADA ADA.Notes
    ## 1         Stair   YES               YES     FULL             FALSE          
    ## 2         Stair   YES               YES     NONE             FALSE          
    ## 3         Stair   YES               YES     FULL             FALSE          
    ## 4         Stair   YES               YES     FULL             FALSE          
    ## 5         Stair   YES               YES     FULL             FALSE          
    ## 6         Stair   YES               YES     FULL             FALSE          
    ##   Free.Crossover North.South.Street East.West.Street Corner Entrance.Latitude
    ## 1          FALSE            4th Ave          25th St     SE          40.66032
    ## 2          FALSE            4th Ave          25th St     SW          40.66049
    ## 3           TRUE            4th Ave          36th St     NW          40.65449
    ## 4           TRUE            4th Ave          36th St     NE          40.65436
    ## 5           TRUE            4th Ave          36th St     NW          40.65468
    ## 6           TRUE            4th Ave          45th St     NE          40.64939
    ##   Entrance.Longitude        Station.Location       Entrance.Location
    ## 1          -73.99795 (40.660397, -73.998091) (40.660323, -73.997952)
    ## 2          -73.99822 (40.660397, -73.998091) (40.660489, -73.998220)
    ## 3          -74.00450 (40.655144, -74.003549) (40.654490, -74.004499)
    ## 4          -74.00411 (40.655144, -74.003549) (40.654365, -74.004113)
    ## 5          -74.00431 (40.655144, -74.003549) (40.654676, -74.004306)
    ## 6          -74.00933 (40.648939, -74.010006) (40.649389, -74.009333)

``` r
# Filter rows where any Route1 to Route11 column contains "A"
a_train_data <- subway_data %>%
  janitor::clean_names() %>%
  filter(if_any(starts_with("Route"), ~ . == "A"))

distinct_a_train_stations <- a_train_data %>%
  distinct(station_name, line) %>%
  nrow()

ada_compliant_a_train_stations <- a_train_data %>%
  filter(ada == TRUE) %>%
  distinct(station_name, line) %>%
  nrow()


distinct_a_train_stations
```

    ## [1] 60

``` r
ada_compliant_a_train_stations
```

    ## [1] 17

60 distinct stations serve the A train, 17 are ADA compliant

## Problem 2: Mr. Trash Wheel dataset

### Read and clean the data

``` r
#Read and clean Mr. Trash Wheel data
mr_trash_wheel_df <- read_excel("data/202309 Trash Wheel Collection Data.xlsx",
                          sheet = "Mr. Trash Wheel",
                          range = cell_cols("A:N"),
                          col_names = TRUE,
                          trim_ws = TRUE,
                          skip = 1) %>%
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>%
  mutate(sports_balls = as.integer(round(sports_balls, 0)),
         csource = "Mr. Trash Wheel")
```

``` r
# Check if sports_balls column exists and mutate only if it does
prof_trash_wheel_df <- read_excel("data/202309 Trash Wheel Collection Data.xlsx",
                          sheet = "Professor Trash Wheel",
                          range = cell_cols("A:M"),
                          col_names = TRUE,
                          trim_ws = TRUE,
                          skip = 1) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  # Conditionally mutate sports_balls if the column exists
  mutate(sports_balls = if ("sports_balls" %in% colnames(.)) as.integer(round(sports_balls, 0)) else NA_integer_,
         csource = "Professor Trash Wheel")
```

``` r
# Check if sports_balls column exists and mutate only if it does
gwynnda_trash_wheel_df <- read_excel("data/202309 Trash Wheel Collection Data.xlsx",
                          sheet = "Gwynnda Trash Wheel",
                          range = cell_cols("A:L"),
                          col_names = TRUE,
                          trim_ws = TRUE,
                          skip = 1) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  # Conditionally mutate sports_balls if the column exists
  mutate(sports_balls = if ("sports_balls" %in% colnames(.)) as.integer(round(sports_balls, 0)) else NA_integer_,
         csource = "Gwynnda Trash Wheel")
```

``` r
#year as character
mr_trash_wheel_df <- mr_trash_wheel_df %>%
  mutate(year = as.character(year))

prof_trash_wheel_df <- prof_trash_wheel_df %>%
  mutate(year = as.character(year))

gwynnda_trash_wheel_df <- gwynnda_trash_wheel_df %>%
  mutate(year = as.character(year))

# combine
combined_trash_wheel_df <- bind_rows(mr_trash_wheel_df, prof_trash_wheel_df, gwynnda_trash_wheel_df)
```

## Exploratory Data Analysis

``` r
summary(combined_trash_wheel_df)
```

    ##     dumpster      month               year          
    ##  Min.   :  1   Length:845         Length:845        
    ##  1st Qu.: 71   Class :character   Class :character  
    ##  Median :162   Mode  :character   Mode  :character  
    ##  Mean   :223                                        
    ##  3rd Qu.:373                                        
    ##  Max.   :584                                        
    ##                                                     
    ##       date                         weight_tons    volume_cubic_yards
    ##  Min.   :1900-01-20 00:00:00.00   Min.   :0.610   Min.   : 5.00     
    ##  1st Qu.:2017-06-21 00:00:00.00   1st Qu.:2.490   1st Qu.:15.00     
    ##  Median :2019-10-25 00:00:00.00   Median :3.070   Median :15.00     
    ##  Mean   :2019-06-08 04:53:06.75   Mean   :3.009   Mean   :15.13     
    ##  3rd Qu.:2021-11-04 00:00:00.00   3rd Qu.:3.540   3rd Qu.:15.00     
    ##  Max.   :2023-06-30 00:00:00.00   Max.   :5.620   Max.   :20.00     
    ##                                                                     
    ##  plastic_bottles  polystyrene    cigarette_butts  glass_bottles   
    ##  Min.   :   0    Min.   :    0   Min.   :     0   Min.   :  0.00  
    ##  1st Qu.:1000    1st Qu.:  280   1st Qu.:  3200   1st Qu.: 10.00  
    ##  Median :1980    Median :  950   Median :  5500   Median : 18.00  
    ##  Mean   :2296    Mean   : 1631   Mean   : 15592   Mean   : 20.89  
    ##  3rd Qu.:2900    3rd Qu.: 2400   3rd Qu.: 16000   3rd Qu.: 28.00  
    ##  Max.   :9830    Max.   :11528   Max.   :310000   Max.   :110.00  
    ##  NA's   :1       NA's   :1       NA's   :1        NA's   :156     
    ##   plastic_bags      wrappers      sports_balls   homes_powered  
    ##  Min.   :    0   Min.   :  180   Min.   : 0.00   Min.   : 0.00  
    ##  1st Qu.:  280   1st Qu.:  840   1st Qu.: 6.00   1st Qu.:37.83  
    ##  Median :  680   Median : 1380   Median :11.00   Median :49.50  
    ##  Mean   : 1082   Mean   : 2330   Mean   :13.17   Mean   :45.87  
    ##  3rd Qu.: 1400   3rd Qu.: 2635   3rd Qu.:18.25   3rd Qu.:57.50  
    ##  Max.   :13450   Max.   :20100   Max.   :56.00   Max.   :93.67  
    ##  NA's   :1       NA's   :118     NA's   :261     NA's   :2      
    ##    csource         
    ##  Length:845        
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ##                    
    ## 

The combined dataset contains data from three trash wheels: Mr. Trash
Wheel, Professor Trash Wheel, and Gwynnda Trash Wheel, with a total of
845 observations. Each observation represents a time when one of the
trash wheels was active, collecting various types of trash. Key
variables include `weight_tons`, representing the total weight of trash
collected (in tons), `plastic_bottles` indicating the number of plastic
bottles collected, and `cigarette_butts`, which tracks the number of
cigarette butts collected. For example, Professor Trash Wheel has
collected a total of 216.26 tons of trash. In June 2022, Gwynnda
collected 1.812^{4} cigarette butts. This dataset provides valuable
insights into the environmental impact of these trash wheels over time.
